packaging_format = 2

id = "emailpoubelle"
name = "EmailPoubelle"
description.en = "Create throwable email address redirected to your real one"
description.fr = "Créez des adresses email jetables qui redirigent les mails vers votre adresse réelle"

version = "2022.06.08~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "Beerware"
website = "https://forge.zici.fr/project/view/6"
demo = "https://poubelle.zici.fr"
code = "https://framagit.org/kepon/emailPoubellePhp"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = false
ldap = false
sso =  false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/poubelle"

    [install.init_main_permission]
    type = "group"
    default = false

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://framagit.org/kepon/emailPoubellePhp/-/archive/d25ae5b243f5dbd8c2b023b80b6406c110843586/emailPoubellePhp-d25ae5b243f5dbd8c2b023b80b6406c110843586.tar.gz"
        sha256 = "4b96d268ecf81684a91c31416b16f2b79a7409416dfd67cdd720d4d13b2ae1d8"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.packaging_format]
    packages = "mariadb-server, php7.4-geoip, php7.4-cli"

    [resources.database]
    type = "mysql"
