test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d83328c3e0d7dbbc317ded2924ac08ba3cc51d3e.name = "Upgrade from 2.0~ynh5"