test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.46ef0790628d7b71b07519d352725dbda4298454.name = "Upgrade from 2022.06.08~ynh1"